### PR TITLE
fix: remove import attributes

### PR DESCRIPTION
**Pull request by NRodriguezcuellar**
### 🔗 Linked issue

#704 

### ❓ Type of change

removed the import attribute 

### 📚 Description

it seems like untyped, a package used by @nuxt/kit can't parse this syntax

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks, but now the build fails with
```
Error: s/nuxt-module build: [error] Module "file:///home/runner/work/storybook/storybook/node_modules/.pnpm/@storybook+core-server@8.2.1_storybook@8.2.1_@babel+preset-env@7.24.7_/node_modules/@storybook/core-server/package.json" needs an import attribute of type "json"
packages/nuxt-module build:   at new NodeError (node:internal/errors:405:5)
packages/nuxt-module build:   at validateAttributes (node:internal/modules/esm/assert:89:15)
packages/nuxt-module build:   at defaultLoad (node:internal/modules/esm/load:103:3)
packages/nuxt-module build:   at ModuleLoader.load (node:internal/modules/esm/loader:417:13)
packages/nuxt-module build:   at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:288:22)
packages/nuxt-module build:   at new ModuleJob (node:internal/modules/esm/module_job:63:26)
packages/nuxt-module build:   at #createModuleJob (node:internal/modules/esm/loader:312:17)
packages/nuxt-module build:   at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:265:34)
packages/nuxt-module build:   at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:251:17)
packages/nuxt-module build:   at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:21)
Error: s/nuxt-module build: [error] Cannot load module. Please check dist: /home/runner/work/storybook/storybook/packages/nuxt-module/dist/module.mjs
```

Do you know what exactly is triggering the issue #704? I'm a bit confused why it refers to babel. I've found a similar error at https://github.com/unjs/listhen/issues/176. But vite, rollup and esbuild all should support import assertions...

**Comment by tobiasdiez** [comment]
I've opened https://github.com/storybookjs/storybook/pull/28594 at the storybook repo for a long-term fix (which would allow us to completely remove the package json import). But it would be good to have a temporary solution until the upstream fix is released. A bit hacky, but perhaps sufficient: just specify an object with a `version` field instead of actually loading the package json file. Could you please give this a try?

**Comment by NRodriguezcuellar** [comment]
Nuxt kit uses untyped which has a dependency on Babel and i believe when using installmodule() it tries to parse the module with Babel but fails because of this syntax, as it didn't need the attribute beforehand I assumpted it would work, but it seems it depends on the node version maybe?

**Comment by NRodriguezcuellar** [comment]
I see you get the error while building while I get the error when running nuxt prepare with the storybook module installed

**Comment by NRodriguezcuellar** [comment]
> I've opened https://github.com/storybookjs/storybook/pull/28594 at the storybook repo for a long-term fix (which would allow us to completely remove the package json import). But it would be good to have a temporary solution until the upstream fix is released. A bit hacky, but perhaps sufficient: just specify an object with a `version` field instead of actually loading the package json file. Could you please give this a try?

Thanks for the context! I can take a look

**Comment by NRodriguezcuellar** [comment]
It could be also Jiti, which may need to be updated to V2

**Comment by tobiasdiez** [comment]
I've now fixed the issue in https://github.com/nuxt-modules/storybook/pull/722. Many thanks for your PR! 🥳

**Comment by NRodriguezcuellar** [comment]
Awesome, hope i can offer some more help in the future 😄

**Pull request closed without merging**
