### PR TITLE
fix: correctly load the storybook preview annotation

### LINKED ISSUE #718: Could not resolve "virtual:nuxt-runtime-config"
I'm getting this error on a clean nuxt project + storybook while running storybook in dev mode (npm run storybook)
Reproduce on stackblitz [https://stackblitz.com/edit/nuxt-storybook-error?file=package.json](https://stackblitz.com/edit/nuxt-storybook-error?file=package.json)
```
✘ [ERROR] Could not resolve "virtual:nuxt-runtime-config"

    node_modules/@storybook-vue/nuxt/dist/preview.mjs:5:30:
      5 │ import { runtimeConfig } from 'virtual:nuxt-runtime-config';
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:nuxt-runtime-config" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "#build/css"

    node_modules/@storybook-vue/nuxt/dist/preview.mjs:6:7:
      6 │ import '#build/css';
        ╵        ~~~~~~~~~~~~

  You can mark the path "#build/css" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "#build/plugins"

    node_modules/@storybook-vue/nuxt/dist/preview.mjs:7:20:
      7 │ import plugins from '#build/plugins';
        ╵                     ~~~~~~~~~~~~~~~~

  You can mark the path "#build/plugins" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.


 ERROR  error while updating dependencies:                                                               9:10:45 PM
Error: Build failed with 3 errors:
node_modules/@storybook-vue/nuxt/dist/preview.mjs:5:30: ERROR: Could not resolve "virtual:nuxt-runtime-config"
node_modules/@storybook-vue/nuxt/dist/preview.mjs:6:7: ERROR: Could not resolve "#build/css"
node_modules/@storybook-vue/nuxt/dist/preview.mjs:7:20: ERROR: Could not resolve "#build/plugins"
    at failureErrorWithLog (/home/yakov/GitHub/KonTxT/KonTxT/node_modules/esbuild/lib/main.js:1472:15)
    at /home/yakov/GitHub/KonTxT/KonTxT/node_modules/esbuild/lib/main.js:945:25
    at /home/yakov/GitHub/KonTxT/KonTxT/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

### PR DESCRIPTION
**Pull request by tobiasdiez**
### 🔗 Linked issue

Fixes #718.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by fabsch225** [comment]
> Does anybody know when this would be released?

not until the ci passes

**Comment by fabsch225** [comment]
Am i correct to assume this fix is implemented in the nightly branch? 
This does indeed fix https://github.com/nuxt-modules/storybook/issues/718, but i get another error instead:

```
Failed to fetch dynamically imported module: http://localhost:6006/node_modules/.cache/storybook/a70f13fdfd1867f0453676d5a644ea8426f743fd81b3af8130df531d6d1cd241/sb-vite/deps/@storybook_addon-essentials_actions_preview.js?v=4a0a96fc
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/react/writing-stories/decorators).
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
```

this is our setup:

image

**Comment by fabsch225** [comment]
Am i correct to assume this fix is deployed in the nightly release? 
This does indeed fix https://github.com/nuxt-modules/storybook/issues/718, but now, insead i get another error:

> [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.
> The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:
> 
> Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/react/writing-stories/decorators).
> Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
> Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
> Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.
>     at useNuxtApp (http://localhost:6006/node_modules/nuxt/dist/app/nuxt.js?v=498ac055:235:13)
>     at useState (http://localhost:6006/node_modules/nuxt/dist/app/composables/state.js?v=498ac055:18:19)
>     at http://localhost:6006/composables/useProductRequestContext.ts:3:29

    
This is our setup rn
image

**Comment by tobiasdiez** [comment]
Please open a new issue with a minimal reproduction (in the best case as a PR modifying https://github.com/nuxt-modules/storybook/tree/main/examples/showcase)

**Pull request merged**
