### PR TITLE
chore: fix linter and update lock file

### PR DESCRIPTION
**Pull request by tobiasdiez**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixes the linter, and revert back to lockfile vs 9.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
This partly reverts https://github.com/nuxt-modules/storybook/pull/684. @chakAs3 not sure what issue you tried to fix with this PR. Does this PR here reintroduces it for you?

**Review by chakAs3 — COMMENTED** [review]
I'm having issues with dependency installation for "nuxt" and "vue". It seems I have two different versions: the latest in the root node_modules and an older version in the storybook-addon package.

I'm confused about managing the versions for the Nuxt module package and the Storybook addon. Should we release them separately with different versions, or should we use a single version for both in each release? Would you help me understand your release strategy?

Additionally, I can't see the playground to test @storybook-vue/nuxt independently. There's only one playground to test the module that has @storybook-vue/nuxt as a dependency.

**Comment by tobiasdiez** [comment]
> I'm having issues with dependency installation for "**nuxt**" and "**vue**". It seems I have two different versions: the latest in the root node_modules and an older version in the storybook-addon package.

If you run `pnpm install` in the root it should use whatever version is specified in the lock file, which is the latest version (compatible with the constraints). Try to delete all `node_modules` folders and then run install again. It also seems that your version of pnpm is quite old.

> I'm confused about managing the versions for the Nuxt module package and the Storybook addon. Should we release them separately with different versions, or should we use a single version for both in each release? Would you help me understand your release strategy?

This still comes from the times where we had two different repos (and hence no version alignment). I agree a consistent version requirement would make sense.

> Additionally, I can't see the playground to test @storybook-vue/nuxt independently. There's only one playground to test the module that has @storybook-vue/nuxt as a dependency.

I moved most of the `@storybook-vue/nuxt` playground to `examples/showcase` so that it can be automatically tested with chromatic. I don't really see the need to have a `@storybook-vue/nuxt`-only test space since the nuxt module just facilitates the development - but if you feel that would be helpful for debugging, we can add another example that uses this package directly.

**Comment by chakAs3** [comment]
Thanks, @tobiasdiez. I’ll try again with the dependencies. Even though I always run git clean -xdf to clear my local files and manually remove node_modules, the lockfile is still causing issues for me.

I will merge this PR then release properly this time ok ?

**Pull request merged**
