### PR TITLE
chore: merge storybook-nuxt repo

### PR DESCRIPTION
**Pull request by tobiasdiez**
Merge the storybook addon () into this repo while preserving the commit history. 

This is needed as https://github.com/nuxt-modules/storybook/pull/592 will integrate the nuxt module closer with the storybook addon, and thus more often simultaneous changes are necessary. Moreover, we don't need to replicate ci and testing infrastructure.

This PR only adds the code and making ci pass. Adding the proper workspace integration and ci builds will be done as follow-ups. 

Please merge this PR and not squash it since otherwise the old commit history is lost.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
@chakAs3 what do you think?

**Comment by chakAs3** [comment]
> @chakAs3 what do you think?

Honestly, making maintenance simpler may seem like a good idea, but it's not quite that simple. The Storybook preset @storybook-vue/nuxt doesn't depend on the Nuxt module, and it shouldn't.

The preset does its own thing in Storybook, while the Nuxt module extends Nuxt app functionalities.

Updating the Nuxt module doesn't affect the Storybook preset.

Usually, we'd follow the same process as with the Next.js preset. Once it's stable, we'll move it to the Storybook monorepo.

I still recommend keeping @storybook/nuxt in a separate repository, linked to nuxt-modules/storybook as a package. This aligns with the practice followed by the Nuxt team for their Nuxi CLI, which is no longer part of the monorepo.

**Comment by tobiasdiez** [comment]
> Honestly, making maintenance simpler may seem like a good idea, but it's not quite that simple. The Storybook preset @storybook-vue/nuxt doesn't depend on the Nuxt module, and it shouldn't.

It was not definitely not my intention to change this. The Storybook addon should still be independent of the Nuxt module. I only would like to have them in the same repository so that
- There is one place to open issues (there were quite a few duplicates and for an average use it's not clear if it's a bug with the nuxt module or with the storybook addon)
- We don't have to duplicate ci infrastructure, eslint + prettier config, etc
- It's easier to make changes that effect both the addon and the nuxt module
- Currently it is possible to break something in the Storybook addon and only realize it once one tries to upgrade the package here in the Nuxt module repo (e.g. because only the tailwind integration is no longer working).

Once the Storybook addon is more stable, we can indeed move it to the storybook repo if they are interested. There is no problem with that.

**Comment by chakAs3** [comment]
@tobiasdiez, we're good on this. I'm completely aligned with you. However, I can't create a merge commit for this; the only option is to squash. That's fine with me since it's still a preview version, and we need to stabilize it more before it's production-ready.

**Comment by tobiasdiez** [comment]
Awesome! Thanks for the feedback. I'll work on the ci integration etc in the coming days.

**Pull request merged**
