### PR TITLE
fix: remove Nuxt context conflict

### LINKED ISSUE #661: Error: [nuxt] instance unavailable / Context conflict
With https://github.com/nuxt-modules/storybook/pull/619, composable and other things using the nuxt instance are generally working. However, sometimes when switching between stories one still gets a `[nuxt] instance unavailable` error.

Todo: find a way to reproduce this reliably and investigate what's the problem

Workaround: refresh the page

### PR DESCRIPTION
**Pull request by obulat**
### 🔗 Linked issue

Related #661

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR updates the global nuxt context, setting its `nuxt` property to the story's nuxt when setting up the current story.

Previously, when navigating from one story to another story, Nuxt would get the context using the app's `_name`, which is the same for all stories, instead of using the `globalName`, which is different for each story.

### CODE REVIEW

**Comment by CarlosZoft** [comment]
@tobiasdiez 

image

**Comment by CarlosZoft** [comment]
@obulat Do you have a temporary solution to this problem?

**Comment by obulat** [comment]
> @obulat Do you have a temporary solution to this problem?

No, unfortunately I don't.

**Comment by tobiasdiez** [comment]
Awesome! On a first glance it looks good to me, will do a bit more testing in a few days and then merge.

**Review by chakAs3 — APPROVED** [review]
Initially, each story in my code had its own Nuxt instance because each story functioned as a separate Vue app mounted in the Storybook canvas. I used the first Nuxt instance as a shared context with the Nuxt app project configuration. However, with recent changes to the package structure, I'm wondering about how it was working previously without this fix. Additionally, these changes have affected my ability to test it before merging or releasing. @tobiasdiez should we start writing tests ?

**Comment by guim4dev** [comment]
kermit

**Comment by tobiasdiez** [comment]
> Initially, each story in my code had its own Nuxt instance because each story functioned as a separate Vue app mounted in the Storybook canvas.

That's still the case. But nuxt has now initial support for multi-app projects, so the global context didn't seem to be necessary anymore.

@obulat what exactly is the need for the global context now? Do you know if 
> Nuxt would get the context using the app's _name, which is the same for all stories

is by design or may be a nuxt bug?

**Comment by obulat** [comment]
> @obulat what exactly is the need for the global context now? Do you know if

>> Nuxt would get the context using the app's _name, which is the same for all stories

>is by design or may be a nuxt bug?

From my research `globalName` was introduced in [Nuxt 2](https://v2.nuxt.com/docs/configuration-glossary/configuration-global-name/#the-globals-property) and the intention was to have it [removed](https://github.com/nuxt/framework/pull/1277) in Nuxt 3. `globalName` is still present in Nuxt3 code, but I think it's not used for anything.

`._name` was introduced in a recent PR that, as you say, @tobiasdiez, started enabling multi-app support in Nuxt: [feat(nuxt): allows the support of multiple shared runtime context](https://github.com/nuxt/nuxt/pull/27068/files)

By default, it is taken from `'#build/nuxt.config.mjs'`:

https://github.com/nuxt/nuxt/blob/8abb1df01783876c3a39a41f24a4f86b12dd81ae/packages/nuxt/src/app/nuxt.ts#L24

Is it possible to set the Nuxt options' `appId` when setting up the Nuxt app in the `preview.ts`? Or would it be better to suggest to Nuxt to make the `_name` configurable in `createNuxtApp` call:

https://github.com/nuxt/nuxt/blob/8abb1df01783876c3a39a41f24a4f86b12dd81ae/packages/nuxt/src/app/nuxt.ts#L251

**Comment by tobiasdiez** [comment]
@obulat Thanks a lot for the investigation. Yesterday, I've created two PRs on the nuxt repo that should implement your findings: https://github.com/nuxt/nuxt/pull/28391 and https://github.com/nuxt/nuxt/pull/28392.

In the meantime we go with your solution, as it is clearly an improvement. I still get context issues in the "docs" section of the storybook, when multiple controls are displayed there. But single stories are working fine.

**Comment by obulat** [comment]
> @obulat Thanks a lot for the investigation. Yesterday, I've created two PRs on the nuxt repo that should implement your findings: [nuxt/nuxt#28391](https://github.com/nuxt/nuxt/pull/28391) and [nuxt/nuxt#28392](https://github.com/nuxt/nuxt/pull/28392).
> 
> In the meantime we go with your solution, as it is clearly an improvement. I still get context issues in the "docs" section of the storybook, when multiple controls are displayed there. But single stories are working fine.

Thank you for all your work investigating and opening new upstream PRs, @tobiasdiez !

**Pull request merged**
